# -*- coding: utf-8 -*-
"""Scoa7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czKoK7Eugi062hokTeCSbeX9UXnjPwLI
"""

!pip install pyswarms

from pyswarms.single.global_best import GlobalBestPSO
from sklearn.datasets import make_blobs
import numpy as np
import matplotlib.pyplot as plt

# === Data ===
X, _ = make_blobs(n_samples=1000, centers=4, cluster_std=0.6, random_state=0)
k = 4  # number of clusters

# === Define cost function for clustering ===
def cost_function(positions):
    n_particles = positions.shape[0]
    cost = np.zeros(n_particles)
    for i in range(n_particles):
        centroids = positions[i].reshape(k, X.shape[1])
        d = np.linalg.norm(X[:, None] - centroids[None, :], axis=2)
        cost[i] = np.sum(np.min(d, axis=1)**2)  # sum of squared distances
    return cost

# === Initialize PSO ===
options = {'c1': 1.5, 'c2': 1.5, 'w': 0.5}
optimizer = GlobalBestPSO(n_particles=50, dimensions=k * X.shape[1], options=options)

# === Optimize ===
best_cost, best_pos = optimizer.optimize(cost_function, iters=150)
best_centroids = best_pos.reshape(k, X.shape[1])

# === Assign clusters ===
distances = np.linalg.norm(X[:, None] - best_centroids[None, :], axis=2)
labels = np.argmin(distances, axis=1)

# === Visualize ===
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis', s=30)
plt.scatter(best_centroids[:, 0], best_centroids[:, 1], c='red', marker='x', s=200, linewidths=3)
plt.title("PSO Clustering (using PySwarms)")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

